// Generated by CoffeeScript 1.8.0
(function() {
  var canvas, win;

  canvas = $('<canvas>');

  win = $(window);

  canvas.addClass('snow');

  win.on('resize', function() {
    var h, w;
    w = win.width();
    h = $(document).height();
    return canvas.attr({
      width: w,
      height: h
    });
  });

  $('body').append(canvas);

}).call(this);
