// Generated by CoffeeScript 1.8.0
(function() {
  var audio, bgmSrc;

  bgmSrc = 'http://static.sdg-china.com/mxd/media/MXDmusic/Bgm04.img.WhiteChristmas.mp3';

  audio = $('<audio>');

  audio.attr({
    src: bgmSrc,
    loop: 'loop'
  });

  audio[0].play();

}).call(this);
