// Generated by CoffeeScript 1.8.0
(function() {
  var audio, bgmSrc, canvas, win;

  canvas = $('<canvas>');

  bgmSrc = 'http://static.sdg-china.com/mxd/media/MXDmusic/Bgm04.img.WhiteChristmas.mp3';

  win = $(window);

  canvas.addClass('snow');

  win.on('resize', function() {
    var h, w;
    w = win.width();
    h = $(document).height();
    return canvas.attr({
      width: w,
      height: h
    });
  }).resize();

  $('body').append(canvas);

  audio = $('<audio>');

  audio.attr({
    src: bgmSrc
  });

  audio[0].play();

}).call(this);
